### ISSUE TITLE
Add SpaceInt Instance

### ISSUE THREAD

**Issue by patchint** [Ahwxorg/LibreY#10]
Hi ! 

That's my instance of LibreY ! 

https://librey.spaceint.fr/

Host in France 

![image](https://github.com/Ahwxorg/LibreY/assets/55617813/5e01b545-62f3-4ca0-b7d5-9d39e19b09e8)

**Comment by codedipper** [comment]
Added in #12

**Comment by Ahwxorg** [comment]
Thanks for hosting LibreY <3

**Comment by Ahwxorg** [comment]
@patchint, your instance seems down. Should I remove it? (Removing if you don't answer in a while)

**Comment by patchint** [comment]
> @patchint, your instance seems down. Should I remove it? (Removing if you don't answer in a while)

I have porn request on it :/

**Comment by Ahwxorg** [comment]
I have a lot as well. You could block using a filter in NGINX (assuming you use NGINX).
