### ISSUE TITLE
Outdated Locales 

### ISSUE THREAD

**Issue by codedipper** [Ahwxorg/LibreY#103]
The locale strings for `nl` and `sv` are outdated. This can cause missing pieces of text, as shown below.
The most common strings I've noticed missing are `category_maps`, `api_unavailable`, and `settings_preferred_engine`, but there may be others.
As a temporary bandage to minimize breakage, we can just put the missing strings in English.
@norrlandxyz @Ahwxorg 

![Screenshot_2023-12-29_18-09-31](https://github.com/Ahwxorg/LibreY/assets/59625582/1f318190-ddf1-4e32-b882-1523d8efadd2)

Added by @Ahwxorg:

- [x] Add needed changes to Dutch (NL) locale file (@Ahwxorg)
- [ ] Add needed changes to Swedish (SV) locale file (@norrlandxyz)

**Comment by davidovski** [comment]
It might be worth merging the locale arrays with the English one, that way any missing text will be filled with the English instead.

**Comment by codedipper** [comment]
> It might be worth merging the locale arrays with the English one, that way any missing text will be filled with the English instead.

Done, the easiest way to do that is with `diff file file` to see if there's any line that doesn't have another one that matches.

**Comment by davidovski** [comment]
What I mean is, perhaps both the current locale and en could be loaded in the PHP code, and merged to avoid any chance that text is missing, though I'm not sure if this is really that necessary if we just keep locale's updated

**Comment by Ahwxorg** [comment]
I'll make a PR for now at least.

**Comment by Ahwxorg** [comment]
I didn't bother with a PR since it's only one line. Merged into main.

**Comment by codedipper** [comment]
@norrlandxyz's email is listed on their profile, they probably won't see this issue but might see the email.
Someone else do it because I still don't have an email server.

**Comment by norrlandxyz** [comment]
Sorry, had GitHub notifications to the wrong mail....
I'll send a PR later today.

**Comment by Ahwxorg** [comment]
No problem, looking forwards to the PR :)

**Comment by Ahwxorg** [comment]
Closing as #106 has been merged.
