### ISSUE TITLE
[Feature Request] Alternative to Youtube Front End

### ISSUE THREAD

**Issue by dCo3lh0** [Ahwxorg/LibreY#108]
I've been using LibreY for some days, but i don't use invidious, instead I've been using piped.video, its way better than invidious, I've looked around here in issues and not found someone asking this question, so I've made it.

**Comment by Ahwxorg** [comment]
> instead I've been using piped.video, its way better than invidious

I disagree. As far as I know, Invidious does not require JavaScript, whilst Piped does.

Anyhow, that does not matter. I'll look into supporting Piped later today.

**Comment by dCo3lh0** [comment]
Oh! i see, its true, piped requires javascript, i'm more saying about the system itself, i think as a user it works better, at least for me. I'm gonna look more into this.

**Comment by davidovski** [comment]
Since piped uses the same URL format as both youtube and invidious, you should be able to use it in the youtube frontend field in the settings: ie `https://piped.video` This should work the same way that you'd expect it to for invidious links or any other privacy frontend. Let me know if that works for you

**Comment by Ahwxorg** [comment]
> Since piped uses the same URL format as both youtube and invidious, you should be able to use it in the youtube frontend field in the settings: ie `https://piped.video` This should work the same way that you'd expect it to for invidious links or any other privacy frontend. Let me know if that works for you

Yes, that's true, but I don't know - and that was what I wanted to test - if the search works without JavaScript, because to my knowledge, php-curl does not execute JavaScript.

**Comment by davidovski** [comment]
thats correct, php-curl simply fetches documents over http, without running any javascript. Using piped as a youtube frontend for redirection shouldn't make much difference, since the target pages will be opened on the user's client.

However as for getting video search results, I don't think there is much reason to be using piped over invidious. When #81 is implemented, it should offer a better solution than relying on a third-party frontend for search results.

**Comment by dCo3lh0** [comment]
i've looked around and there is lighttube as well, but does use javascript too, so nothing too much different.

**Comment by Ahwxorg** [comment]
> thats correct, php-curl simply fetches documents over http, without running any javascript. Using piped as a youtube frontend for redirection shouldn't make much difference, since the target pages will be opened on the user's client.

Of course, I understand, but I was wondering if Piped uses JavaScript to make requests to get queries or not. That's what I wanted to check.

**Comment by Ahwxorg** [comment]
It sort of works - using piped.video - but sadly I don't get the thumbnails back. That should be an easy fix, however.

And using the default with Invidious, we get the following back:
![image](https://github.com/Ahwxorg/LibreY/assets/87855602/7d8d4d17-a4ca-4bc2-8fae-7013c6d396cc)

**Comment by dehlirious** [comment]
> It sort of works - using piped.video - but sadly I don't get the thumbnails back. That should be an easy fix, however.
> 
> And using the default with Invidious, we get the following back: ![image](https://private-user-images.githubusercontent.com/87855602/297766679-7d8d4d17-a4ca-4bc2-8fae-7013c6d396cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzU4MTAsIm5iZiI6MTcwNTYzNTUxMCwicGF0aCI6Ii84Nzg1NTYwMi8yOTc3NjY2NzktN2Q4ZDRkMTctYTRjYS00YmMyLThmYWUtNzAxM2M2ZDM5NmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMzgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTZmYzcxMWU5NzRlZWI5MGUzYzdkNzY0ZmNmOTMwYzZiODc2YjA2NjMwMTU2M2E3ZmRlYWJhM2QzZjVmZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X-EHmCY8wtLh0BoRksI4NQFrPff2FcZIYHNZvVW26M8)

You can always use `https://i.ytimg.com/vi/VIDEO_ID/maxresdefault.jpg` e.g.  `https://i.ytimg.com/vi/Axx9IMdL4jc/maxresdefault.jpg` ,

On my instance, this is broken But I assume it works with the latest up to date version `/LibreY/image_proxy.php?url=https://i.ytimg.com/vi/Axx9IMdL4jc/maxresdefault.jpg`

**Comment by Ahwxorg** [comment]
> On my instance, this is broken But I assume it works with the latest up to date version /LibreY/image_proxy.php?url=https://i.ytimg.com/vi/Axx9IMdL4jc/maxresdefault.jpg

No, because it's not added to the trusted proxy domains. That might be a good way to fetch images though!

**Comment by codedipper** [comment]
https://docs.piped.video/docs/api-documentation/#streamsvideoid

But _why_? It's a backend change, so it makes no difference in what the user experiences. One can already used Piped as a frontend as explained [here](https://github.com/Ahwxorg/LibreY/issues/108#issuecomment-1898166481).

**Comment by Ahwxorg** [comment]
As of the latest commit (at time of writing), we use YouTube directly for the thumbnails, which makes it so that Piped or other instances should work!
