### ISSUE TITLE
Should donations to LibreX be removed?

### ISSUE THREAD

**Issue by SectorV5** [Ahwxorg/LibreY#113]
If the author of LibreX is really deceased like this Github issue https://github.com/hnhx/librex/issues/274 claims it to be, wouldn't it be a waste of money, all those crypto currencies going to a wallet of a deceased person, which will never be accessed. 

I know this is a really sad story if true, but I still think that for the survival of this project, the author would've probably wanted this, for the donations to go to LibreY so that it can continue to improve.

**Comment by davidovski** [comment]
I think that maybe a donation address for the LibreY project should only be included and then a portion of the donations could be donated back to hnhx. I don't really think it makes sense for the wallet for LibreX to be listed first either way. 

Also, if there are people willing to donate, it would be appreciated if LibreY contributors would get a share, due to all of the work put into the project.

**Comment by davidovski** [comment]
Just to add, the original code for LibreX includes this comment:
```
    // Feel free to add your donation options here, but please don't remove mine.
```
Not sure how legally binding a comment like this is, but its good to err on the side of caution. It would be best if we leave the original donation options there, if nothing but to respect this request.

**Comment by Ahwxorg** [comment]
> If the author of LibreX is really deceased like this Github issue [hnhx#274](https://github.com/hnhx/librex/issues/274) claims it to be, wouldn't it be a waste of money, all those crypto currencies going to a wallet of a deceased person, which will never be accessed.
> 
> I know this is a really sad story if true, but I still think that for the survival of this project, the author would've probably wanted this, for the donations to go to LibreY so that it can continue to improve.

That does not feel right, @hnhx did a lot of work on LibreX, and I am not removing their donation link "just because". I don't think people donate that much either way... And if they do, hnhx can buy a cup of coffee or whatever they might want I suppose...

**Comment by Ahwxorg** [comment]
> Also, if there are people willing to donate, it would be appreciated if LibreY contributors would get a share, due to all of the work put into the project.

I also second this, @codedipper and you did most of the work on the major changes after forking from LibreX.

**Comment by codedipper** [comment]
1. [They probably did not die.](https://github.com/hnhx/librex/issues/274#issuecomment-1902454086)
2. I only use XMR wallets over Monero onion service nodes under Whonix, which I haven't gotten working so I basically haven't accessed my crypto wallets for a year.

**Comment by codedipper** [comment]
After 3 days of syncing the Monero blockchain and also completely filling my hard drive, I once again have access to my main XMR wallet:
`44hgaAwyYFxFoz3b9kEUsvXvwkt2tq3ruQoJWVAgoEpocvXtr7oETnTi4ZpbSFtCwKRSKvqXkd3iRDm3tdzXP3THTUj1wG9`

If you must send any money to this address, it will probably just end up being donated to [the Tor Project](https://donate.torproject.org/cryptocurrency/) or [Tails](https://tails.net/donate/).

**Comment by Ahwxorg** [comment]
I should donate my 70 cents to Tor too, probably :)

**Comment by dehlirious** [comment]
> After 3 days of syncing the Monero blockchain and also completely filling my hard drive, I once again have access to my main XMR wallet:
> `44hgaAwyYFxFoz3b9kEUsvXvwkt2tq3ruQoJWVAgoEpocvXtr7oETnTi4ZpbSFtCwKRSKvqXkd3iRDm3tdzXP3THTUj1wG9`
> 
> I don't want any money; if you must send any coins to this address, it will probably just end up being donated to [the Tor Project](https://donate.torproject.org/cryptocurrency/) or [Tails](https://tails.net/donate/).

Great sediment, sidenote, have you tried qubes? Kodachi, slightly different is ParrotOS. There's also kicksecure. I can't remember but I believe I like kodachi the most so far.

**Comment by codedipper** [comment]
> Great sediment, sidenote, have you tried qubes? Kodachi, slightly different is ParrotOS. There's also kicksecure. I can't remember but I believe I like kodachi the most so far.

Qubes is awesome. It's just the very steep learning curve and the thought of reinstalling my main OS once more that keeps me from installing it. If I break my computer again I'll definitely give it a shot. I am extremely unfamiliar with those other operating systems, except that I know Whonix is based off of Kicksecure. The OpenBSD Project does not accept Monero donations. :cry:
