### ISSUE TITLE
Can't Add LibreY as Search Engine on Mozilla-based Web Browsers

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [Ahwxorg/LibreY#128]
This is what happens when I try to do it:

![Screenshot_20240302_110000](https://github.com/Ahwxorg/LibreY/assets/7718402/5bafe915-2a3f-4215-9a9a-ac030259d626)

It works as intended for Chromium-based ones, like Brave or Ungoogled Chromium.

**Comment by dehlirious** [comment]
Had never heard of LibreWolf before. 

Hmm.. Let's look at an example of a working websites opensearch prior to diagnosing.

`https://mycroftproject.com/opensearch.xml?method=POST`


And, Let's refer to [https://developer.mozilla.org/en-US/docs/Web/OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch)

The issue ended up being

`  <Url type="application/opensearchdescription+xml" rel="self" template="/opensearch.xml"/>`

Needs to be 

`  <Url type="application/opensearchdescription+xml" rel="self" template="https://DOMAIN.NET/opensearch.xml"/>`
