### ISSUE TITLE
[Feature Request] Ability to specify default theme

### ISSUE THREAD

**Issue by OdinVex** [Ahwxorg/LibreY#135]
I'm not one for AMOLED, the ability to specify a `CONFIG_...` for default theme would be nice. Currently hijacked the Docker's entrypoint to sed replace `?? "amoled"` to `?? "auto"`.

Edit for others (replace auto with whatever theme name you want, use the HTML value): `entrypoint: /bin/sh -c "sed -i \"s/?? \\\"amoled\\\"/?? \\\"auto\\\"/g\" /var/www/html/misc/header.php; sed -i \"s/?? \\\"amoled\\\"/?? \\\"auto\\\"/g\" /var/www/html/misc/search_engine.php; docker/entrypoint.sh"`

**Comment by codedipper** [comment]
Willing to implement this.
Also noting files in `/misc/search_engine.php` and `/settings.php` need to also be changed.

**Comment by davidovski** [comment]
could be good for to add as option in config.php too of course

**Comment by codedipper** [comment]
This should be closed.

**Comment by codedipper** [comment]
> Is setting the theme possible via an environmental variable or setting without needing to hijack the entrypoint to `sed` or modifying files?

Yes! Eventually it'll be merged into main from #167

**Comment by Ahwxorg** [comment]
It has been merged!
