### ISSUE TITLE
New instance: librey.nirn.quest

### ISSUE THREAD

**Issue by hyperreal64** [Ahwxorg/LibreY#147]
Location: United States
CDN: No
URL: https://librey.nirn.quest

**Comment by Ahwxorg** [comment]
I'll look at this next week, life is a bit busy.

**Comment by codedipper** [comment]
Are you sure your instance is located in the United States?

![image](https://github.com/Ahwxorg/LibreY/assets/59625582/1b3a3aca-e4ad-4feb-989f-a5804b1ca8ff)

**Comment by hyperreal64** [comment]
Oh, my apologies! I forgot I selected the Toronto data center on Digital Ocean. So yeah it's located in CA.

**Comment by hyperreal64** [comment]
The new server location is Chicago, IL, USA.
