### ISSUE TITLE
Removing my Instance

### ISSUE THREAD

**Issue by Retro-Hax** [Ahwxorg/LibreY#153]
So i just thought itd say that i honestly want my Instance removed especially since i had lots of troubles maintaining it and even now i resetting it up on a new server i am just getting issues and so i just rather leave it in the dust
![image](https://github.com/Ahwxorg/LibreY/assets/69952967/34b5408c-2340-4b2f-94fa-f479592bbf60)

Depending on the Instance its either librex.retro-hax.net or librey.retro-hax.net but its probably one of those two

**Comment by Ahwxorg** [comment]
[Changed in commit 86989708211db5f0acc33a1b43841bba4324431b](https://github.com/Ahwxorg/LibreY/commit/86989708211db5f0acc33a1b43841bba4324431b)
