### ISSUE TITLE
Duplicate setting on Settings Page setting.php

### ISSUE THREAD

**Issue by rjc3rd** [Ahwxorg/LibreY#156]
Number of results per page

Is showing two times on the Setting Page.

**Comment by rjc3rd** [comment]
Plus no matter what number I select here, I get a random number of results. 10 -25 per page.

**Comment by Ahwxorg** [comment]
![image](https://github.com/Ahwxorg/LibreY/assets/87855602/92776197-544d-47fc-b86e-c39f426b6ae5)
It looks like the code is double too, I asked the person that added it about this issue.

**Comment by rjc3rd** [comment]
I just removed one of them on my instance.

@Ahwxorg Take a look at how I set up my Settings Page.
https://search.libre.wtf/settings.php

I think it looks cleaner, but still has the same settings as yours.
What do you think?

**Comment by Ahwxorg** [comment]
Issue has been fixed in [commit 3f26e8834ca8d5d67e8137e7905ff8c93311f661](https://github.com/Ahwxorg/LibreY/commit/3f26e8834ca8d5d67e8137e7905ff8c93311f661).
