### ISSUE TITLE
My "fix" caused a different problem with "sticking" settings.

### ISSUE THREAD

**Issue by rjc3rd** [Ahwxorg/LibreY#159]
So, if you go to settings and change something like theme to light on the first try. Works and the cookie is updated to light. Then you go back to change it back to dark, and it works, then you go back and change it to startpage, and it works.

The problem is that when you went the first time you also set safe search on. When you went back the second time, it was still set, but you changed your mind, and unchecked it. But every time after that and you go back to settings, it still set to safe search. It won't unset. 

Since there is a different cooking setting for theme each time, it gets updated. but "checked" is the only setting for safe search. Unchecking it doesn't actually set a new cookie setting, so it doesn't get unchecked. and won't until you click reset, which destroys ALL cookie settings back to default. Which in this case is safe search unchecked.

I think maybe it was better to have it reset cookies each time you click save, the way it was before.

**Comment by Ahwxorg** [comment]
I'll make a reset button, that might be the best solution.

**Comment by davidovski** [comment]
Isn't there already a reset button? iirc all it does it clears all the cookies, which should reset all of the user's settings

**Comment by Ahwxorg** [comment]
I forgot that lol, think this issue can be closed then? I might add a little text to the reset button saying that people should click that if their settings "act weird".

**Comment by rjc3rd** [comment]
So I'm pretty sure this is only a "problem" for the 3 check boxes. So a note would only need to say that checking the checkbox can only be cleared by reseting all settings.

Setting the checkbox can only be cleared by using the Reset button below.

Something like that, maybe.

**Comment by Ahwxorg** [comment]
I have this on a local branch, I'm doing a bigger PR sometime soon I think.
