### ISSUE TITLE
Video thumbnails are sometimes broken

### ISSUE THREAD

**Issue by codedipper** [Ahwxorg/LibreY#170]
Example:

https://search.ahwx.org/search.php?q=Italy+losing+the+Euro+Cup+2024&p=0&t=2&nf=1
![image](https://github.com/Ahwxorg/LibreY/assets/59625582/f652f158-212f-4f1b-aa7f-18b12297ab0e)

Reproduce:
1. Apply #169 patch or disable frontends.
2. Make a video search; repeat until you see a result with a missing thumbnail.

Solution:
Sometimes `/maxresdefault.jpg` doesn't return a real thumbnail.
A fix is to switch it to `/mqdefault.jpg` or `/default.jpg` on line 53 of `engines/invidious/video.php`, although the resulting thumbnail will be at a lower quality.

**Comment by Ahwxorg** [comment]
Fixed in local branch, will be pushed soon.
