### ISSUE TITLE
No search results on openBSD

### ISSUE THREAD

**Issue by ILoveLinux666** [Ahwxorg/LibreY#178]
Hello, I realize that this is a very niche issue.

The problem I am facing is that searches always return "No results found. Unable to fallback to other instances." I've had this problem while running LibreY on debian boxes but it was always temporary.

But when hosting on openbsd with httpd (not apache) the problem seems permanent. I had other issues when trying to set LibreY up but they were easily fixable. This one is more elusive (at least to me it is). PHP doesn't throw any errors, the searches just do nothing.

I can provide logs or configs :]

**Comment by Ahwxorg** [comment]
I see that you've closed this issue. Has it been resolved?

**Comment by Ahwxorg** [comment]
If so, could you drop some info on how you did that here? It might be interesting for others :)

**Comment by codedipper** [comment]
Some php modules required by LibreY are just completely missing from ports, so the issue persists in any web server, OpenHTTPd and nginx included. I forget which ones are the culprit, but you can check the error log outputs to find out. Tools to compile php modules are also missing from ports, so best of luck.
