### ISSUE TITLE
Problem running LibreY on port libre-find.online:8888

### ISSUE THREAD

**Issue by robert-winkler** [Ahwxorg/LibreY#184]
Hi,  I just installed LibreY on my server libre-find.online. Since YaCy is running there already as main crawler and search engine (sic!),  I would like to use 8888 as alternative port for LibreY, using the the following nginx configuration as a separate file in sites-enabled:

~~~
server {
        listen 8888;
        server_name libre-find.online;

        root /var/www/html/LibreY;
        index index.php;

        location ~ \.php$ {
               include snippets/fastcgi-php.conf;
               fastcgi_pass unix:/run/php/php-fpm.sock;
        }
}
~~~

`nginx -t` and `nginx -s reload` report no error.
As well, the service php8.2-fpm starts without error.

However,  I'm getting the error: Connection refused,  ERR_CONNECTION_REFUSED

Is there anything wrong with my installation (e.g., do I have to chown www-data as with apache? I'm new to nginx), or with my nginx configuration?

**Comment by codedipper** [comment]
> However, I'm getting the error: Connection refused, ERR_CONNECTION_REFUSED

Sounds a lot like you just forgot to open the port in your firewall. It could also be that php-fpm is denying the connection from nginx itself, but I have no clue what that is if there are no error logs. For the latter case, the file permissions on php-fpm's unix socket might deny access to nginx or it might've hit php-fpm's rate limit somehow. Both can be changed in whatever files you find in `/etc/php/php-fpm*`. The owner and group of php-fpm's unix socket and LibreY's source code directory should be set to the same as the user/group nginx runs as.

**Comment by robert-winkler** [comment]
Thanks a lot!
I managed the installation on libre-find.online 😉.

[Robert Winkler - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2sz4jp)	[2sz4jp]

On October 6, 2024 at 3:16 GMT, codedipper ***@***.***> wrote:

However, I'm getting the error: Connection refused, ERR_CONNECTION_REFUSED

Sounds a lot like you just forgot to open the port in your firewall. It could also be that php-fpm is denying the connection from nginx itself, but I have no clue what that is if there are no error logs. For the latter case, the file permissions on php-fpm's unix socket might deny access to nginx or it might've hit php-fpm's rate limit somehow. Both can be changed in whatever files you find in /etc/php/php-fpm*. The owner and group of php-fpm's unix socket and LibreY's source code directory should be set to the same as the user/group nginx runs as.

**Comment by Ahwxorg** [comment]
Is this issue still open?

**Comment by robert-winkler** [comment]
Hi, reinstalled the server with only LibreY. Now it's running fine 🙂.

[Robert Winkler - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2t4gah)	[2t4gah]

On October 10, 2024 at 8:35 GMT, Ahwx ***@***.***> wrote:

Is this issue still open?

**Comment by robert-winkler** [comment]
Hi, I managed a fresh install on :80. Thanks!

**Comment by Ahwxorg** [comment]
Great!
