### ISSUE TITLE
Adding an instance to the list

### ISSUE THREAD

**Issue by robert-winkler** [Ahwxorg/LibreY#188]
Hi, my instance is up and running.
1) How could I add it to the list of LibreY instances?
2) Would this be a huge load?
Best, R

**Comment by Ahwxorg** [comment]
1. You can edit instances.json and make a PR. That'd be the best way.
2. The more instances, the littler load (due to the fallback API), so your instance will get a little bit of the traffic from the network. You should expect more traffic, but it's perfectly doable and takes little resources in my experience. You will get ratelimited faster. If you have issues with that, you can always disable the API in the config.

**Comment by robert-winkler** [comment]
"Pull request creation failed. Validation failed: must be a collaborator"
Anyway, attached the modified instances.json
Have fun, Robert

[Robert Winkler - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2tju5a)	[2tju5a]

On October 18, 2024 at 9:26 GMT, Ahwxorg/LibreY ***@***.***> wrote:

- You can edit instances.json and make a PR. That'd be the best way.
- The more instances, the littler load (due to the fallback API), so your instance will get a little bit of the traffic from the network. You should expect more traffic, but it's perfectly doable and takes little resources in my experience. You will get ratelimited faster. If you have issues with that, you can always disable the API in the config.

**Comment by robert-winkler** [comment]
Sorry, I had a typo in my URL..
it must be:
~~~
{
"clearnet": "[https://libre-find.online/",](https://libre-find.online/)
"tor": null,
"i2p": null,
"country": "DE",
"librey": true
}
the place of the server is DE; the funding comes from MX 😉

~~~

[Robert Winkler - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2tjvo9)	[2tjvo9]

On October 18, 2024 at 20:19 GMT, Robert Winkler ***@***.***> wrote:

"Pull request creation failed. Validation failed: must be a collaborator"
Anyway, attached the modified instances.json
Have fun, Robert

[Robert Winkler - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2tju5a)	[2tju5a]

On October 18, 2024 at 9:26 GMT, Ahwxorg/LibreY ***@***.***> wrote:

- You can edit instances.json and make a PR. That'd be the best way.
- The more instances, the littler load (due to the fallback API), so your instance will get a little bit of the traffic from the network. You should expect more traffic, but it's perfectly doable and takes little resources in my experience. You will get ratelimited faster. If you have issues with that, you can always disable the API in the config.

**Comment by robert-winkler** [comment]
[instances.json](https://github.com/user-attachments/files/17440605/instances.json)

**Comment by Ahwxorg** [comment]
Weird, you should be able to fork the repository, edit the file and make a PR, but I'll add it by hand :).

**Comment by Ahwxorg** [comment]
Added in [a1476a81dc5de062c28dadbbd69cf881be7d6dfc](https://github.com/Ahwxorg/LibreY/commit/a1476a81dc5de062c28dadbbd69cf881be7d6dfc)
