### ISSUE TITLE
Upgrading instance from GitHub 

### ISSUE THREAD

**Issue by robert-winkler** [Ahwxorg/LibreY#191]
Hi,  can I upgrade LibreY by just `git pull`, or will this overwritten my configuration?
Sorry for asking such trivial questions but I had a bad `rm -Rvf .*` experience this week.

**Comment by Ahwxorg** [comment]
That should be fine, since the file you're generally editing have the .example suffix in the  config. To be extra safe, you can always just make a backup like so:

```sh
cp -r librey librey-bak
```
