### ISSUE TITLE
Video time

### ISSUE THREAD

**Issue by caywin25** [Ahwxorg/LibreY#193]
Hello 

When we choose a video is it possible to add the total time of each video listed? 

I find it very useful :) 
Thanks

**Comment by Ahwxorg** [comment]
That should be doable, I'll add a help wanted label for now!

**Comment by Ahwxorg** [comment]
I've drafted up a quick version locally, this is pretty easy do to and very possible, am working on it :)

**Comment by caywin25** [comment]
Thank you very much :+1:

**Comment by Ahwxorg** [comment]
I can't get the json query to work. I know that Invidious returns time in seconds, and that should be pretty easy to parse and create a span for, but it just does not output anything for me.

**Comment by Ahwxorg** [comment]
Time has been added in seconds. Should move to human readable formats, but don't have the time to write a function for that _right now_, will do soon!

**Comment by Ahwxorg** [comment]
Added in [4d862ce801dae2b4797b910259f921964c3ef35c](https://github.com/Ahwxorg/LibreY/commit/4d862ce801dae2b4797b910259f921964c3ef35c)!
