### ISSUE TITLE
why don't you allow us to fork and depoly librey

### ISSUE THREAD

**Issue by osarthak** [Ahwxorg/LibreY#20]
i would like to make an instance of librey

**Comment by codedipper** [comment]
LibreY is licensed under the GNU GPL v3.0, so you are allowed modify and distribute the code as long as you release it under the same license and release the source code. There is a [wiki article](https://github.com/Ahwxorg/LibreY/wiki/How-to-host-LibreY) showing how one can host LibreY, or you can use the [Docker image](https://github.com/Ahwxorg/LibreY/tree/main/docker#readme).

**Comment by osarthak** [comment]
got error while using ur docker-compose : repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
and can't fork because already have forked librex?

**Comment by davidovski** [comment]
It seems that LibreY isn't actually on the docker hub as the wiki claims, likely just missed out accidently. We will work on getting it on there. 

However in the mean time, try building the docker image manually, using `docker build . -t   librey/librey:latest` and then running as you would. Let us know if that works by itself. Thanks

**Comment by osarthak** [comment]
> docker build . -t librey/librey:latest

yes it worked, thanks!
any solution on forking librey, I can't fork it. says "No available destinations to fork this repository."

**Comment by davidovski** [comment]
I have fixed the error that stopped the LibreY docker from being created and starting properly; the commit is included in the next PR #19, so it should work once that PR is merged :+1: 

As for forking, you should be able to fork this repository on github, or on any other platform. If you already have a repository that is forked from LibreY, just change the upstream url to this one and pull the changes.
