### ISSUE TITLE
Dealing with spammers

### ISSUE THREAD

**Issue by davidovski** [Ahwxorg/LibreY#21]
I've noticed that quite often my instance gets barraded with hundreds of requests with identical queries. From inspecting these queries, I've come to the conclusion that they are being sent from an automated script of some sort. These spammed requests end up causing an instance to quickly ratelimited by Google and then with the fallback feature, other instances also fall victim.

While I do appreciate that LibreX/Y's api is a very simple and easy way to get search results, its important to understand that the amount of queries that it can handle is limited by how much Google will allow before ratelimiting any particular instance. 

So to whoever is using LibreX/Y in their scripts/services: *Please consider slowing down the amount of requests you are making, especially for the same query. Google will not give a different set of results if you give it the same query 7 times a second, so there is no need for you're script to be checking that much!*

Annoyed rant aside, I think that it might be worth adding some more caching to LibreY, to combat this problem. If two queries have been made in a certain amount of time are identical, there is no reason we should be making an extra request to Google for it: the first result could be cached and served immediately if it was found. This could easily reduce the total number of requests being made by all LibreY instances towards Google, and greatly increase the chances of getting an actual result when you want to make a query.

I see how this could be a move against LibreX's original philosophy, since caching Google results could be seen as a privacy issue. However, I believe that if we cached only the results and the query/request url, then there is little way that it could be used to link them to a specific user. Furthermore, these results will only be cached for a limited amount of time and if implemented correctly, will only be stored in working memory (if that makes a difference)

Please let me know what you think and if some simple form of results caching should be implemented in LibreY or not, or if you have any other solutions for how to solve the spammer issue. Thank you!

**Comment by Ahwxorg** [comment]
@Kacper-Mlynarczyk [HTTP error 500](https://http.cat/500) is an internal server error. Likely to be something with PHP.

**Comment by Ahwxorg** [comment]
I honestly have no idea how to get caching to work inside of PHP without some sort of persistent database which is something I'd rather not do since you'd need a lot more dependencies and that'd be harder on resources, as well as not ideal seeing how NGINX can handle caching iirc.

**Comment by codedipper** [comment]
> @Kacper-Mlynarczyk [HTTP error 500](https://http.cat/500) is an internal server error. Likely to be something with PHP.

No, it may have something to do with rate limiting.

![Screenshot_2023-08-29_12-19-50](https://github.com/Ahwxorg/LibreY/assets/59625582/1a9844e8-46dc-4946-b397-4ecf13cd2009)

**Comment by Ahwxorg** [comment]
Ah alright I thought it was something with PHP...

**Comment by Ahwxorg** [comment]
Closed it on accident.

**Comment by codedipper** [comment]
> > > @Kacper-Mlynarczyk [HTTP error 500](https://http.cat/500) is an internal server error. Likely to be something with PHP.
> > 
> > 
> > No, it may have something to do with rate limiting.
> 
> Yeah it was funny because other search queries such as imaage or torrents worked but the generic search didn't. But thank you for answering.

Yes, because they use different engines and connect to different domains.

Also, the reason it returns with HTTP error code 500 is because sometimes when you're rate limited, the server (PHP) does not expect the response it got back and corrupts the rest of the document (as seen below). So the document is invalid and obverse a 500 error code on the server side because there was a server-side error!

![Screenshot_2023-08-29_15-49-06](https://github.com/Ahwxorg/LibreY/assets/59625582/26f3377e-61e9-4c2e-8c20-2d167b966ebc)

**Comment by Ahwxorg** [comment]
Ah. That makes sense.
