### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by patchint** [Ahwxorg/LibreY#25]
We need something to block spamming with the same queries, because I have the same IP spamming for porn through the API :')
![image](https://github.com/Ahwxorg/LibreY/assets/55617813/2a8f2152-6cea-4b8e-be4f-49f67d089c49)
![image](https://github.com/Ahwxorg/LibreY/assets/55617813/3d8ab254-cb75-45c8-a98e-c5a50218e17b)
![image](https://github.com/Ahwxorg/LibreY/assets/55617813/0a97cbd2-1d2b-41ad-99f5-d03aed8d5943)

And there's a lot more of IP addresses, so for now I'm just blocking them with NGINX, but we need to block porn queries on the API

**Comment by kubo6472** [comment]
Check #21

**Comment by Ahwxorg** [comment]
As of the latest commit, caches have been implemented, so that LibreY caches queries and it should work way better. Please join #librey:ahwx.org if you want to stay updates on stuff about LibreY.
