### ISSUE TITLE
Add librey.baczek.me

### ISSUE THREAD

**Issue by Wint3rmute** [Ahwxorg/LibreY#45]
Hello! Thanks for forking LibreX and keeping it up-to-date :)

My instance is right here: https://librey.baczek.me/

It's hosted in Poland

**Comment by Ahwxorg** [comment]
![image](https://github.com/Ahwxorg/LibreY/assets/87855602/69dd398e-8065-4b7d-a9a2-db796411326a)
It seems like this instance is not hosted in Poland but rather in France by OVH.

What are you on about?

**Comment by Wint3rmute** [comment]
@Ahwxorg weird, OVH's page tells me that the server is hosted in Poland:

![image](https://github.com/Ahwxorg/LibreY/assets/19196352/e6bfb2e0-9e10-46ad-925a-e87a49f8187f)

**Comment by Ahwxorg** [comment]
Do a dig on it yourself and see :L

**Comment by davidovski** [comment]
[iplocation.net](https://www.iplocation.net/ip-lookup) shows the ip as poland from all but one source, I think its safe to say that its in Poland.

 Geo-locating IP addresses is a bit of a weird thing, quite often no 1 database is completely accurate: my VPS (for [davidovski.xyz](https://search.davidovski.xyz) )  is in the UK, at least it should be, but some sources report it incorrectly as Germany (including Google!!).

**Comment by Wint3rmute** [comment]
+1 on @davidovski, I can say from experience that those IP location services often contain outdated information, the most accurate & recent data is usually available only on paid subscriptions

**Comment by Ahwxorg** [comment]
I think OVH then passed the IP over to one of their Poland machines. I thought it was quite weird, but I'll just accept it. Thanks for hosting!
