### ISSUE TITLE
No instance list

### ISSUE THREAD

**Issue by davidovski** [Ahwxorg/LibreY#5]
Since the repo for libreX seems to be dead for now, it might be worth migrating the instances table in README and all of `instances.json`. 

The list of instances in `instances.json` is important for the librex fallback feature when a google search fails, so as many as possible LibreX instances should be listed in there.

As for the README, maybe a table could be made listing all the LibreX and LibreY instances, with a flag or something indicating that one is running LibreX. Maybe this could be moved to a new page (or even generated via instances.json on the instance itself?)

**Comment by Ahwxorg** [comment]
That's a good idea. Do you have any idea on how to generate this list?
