### ISSUE TITLE
New instance of Librey - https://librex.supernets.org

### ISSUE THREAD

**Issue by acidvegas** [Ahwxorg/LibreY#54]
Appreciate it if you would add our instance to your list, we plan to keep this one up, updated frequent & and tor/i2p support soon.

The domain will remain librex, since it is established already, but it is currently running LibreY latest version.

Was running librex until @codedipper pointed out this fork to me

**Comment by codedipper** [comment]
#53 :)

**Comment by Ahwxorg** [comment]
Closed by #53
