### ISSUE TITLE
New instance

### ISSUE THREAD

**Issue by unstablemaple** [Ahwxorg/LibreY#55]
I have a LibreY instance hosted on: [search.seitan-ayoub.lol](https://search.seitan-ayoub.lol). 
Location: DE
CDN: No

**Comment by codedipper** [comment]
**Batter's Box for $19.99 at Mary Brown's**
Get 6 pieces of our Signature Chicken, Medium Taters, 2 Biscuits and a Medium Gravy for ONLY $19.99!

**Comment by Ahwxorg** [comment]
Closed by pull #56
