### ISSUE TITLE
Wikipedia results sometimes have no language

### ISSUE THREAD

**Issue by davidovski** [Ahwxorg/LibreY#57]
When searching on some instances (ie [search.davidovski.xyz](https://search.davidovski.xyz/) wikipedia results show when they shouldn't, linking to a wikipedia page that has no language specified (`.wikipedia.org`)

This is likely a mistake made in #50 when changing how languages are dealt with.

**Comment by codedipper** [comment]
`bem` and `bt` do not exist.
`ws` is not the correct code for Samoa, it is `sm`.
`ak` exists but is completely empty.
`km` is in fact an allowed language.

Also just make English the default if it doesn't exist.

**Comment by davidovski** [comment]
I'm a bit busy these days to see exactly what the problem is, but if i remember correctly I think I tried setting the domain to simply "wikipedia.org" if no language was specified. (Might be an issue when falling back to outdated instances)

**Comment by davidovski** [comment]
Is this still an issue? I think it was mostly due to API changes with languages in LibreY that caused it during fallback. I haven't seen it in a while, guessing due to fallback instances being updated? 
Can someone confirm that this issue no longer happens?

**Comment by davidovski** [comment]
I think its safe to close this issue now, will reopen if the bug re-occurs
