### ISSUE TITLE
Dead instances

### ISSUE THREAD

**Issue by acidvegas** [Ahwxorg/LibreY#63]
The following instances are no longer active and can be removed from `instances.json`
- https://librex.me/
- https://librex.revvy.de/
- https://lx.vern.cc/

**Comment by codedipper** [comment]
Librex.me and librex.revvy.de still have Tor and I2P working, but I still wanted to keep it listed, and not keep just `null` for clearnet because I thought it might break instance fallback.
Also https://librey.spaceint.fr/

**Comment by codedipper** [comment]
https://librex.yogeshlamichhane.com.np/ includes a JavaScript captcha for Tor users.

**Comment by davidovski** [comment]
Javascript captcha for tor users could affect instance fallback, so this might be a reason to remove it? (of course besides privacy implications)

**Comment by Ahwxorg** [comment]
See commit [dd32e2bb5ed39d88d1227f2f148aec057352a3c0](https://github.com/Ahwxorg/LibreY/commit/dd32e2bb5ed39d88d1227f2f148aec057352a3c0).
