### ISSUE TITLE
Previews

### ISSUE THREAD

**Issue by ShalokShalom** [Ahwxorg/LibreY#64]
There is this [awesome feature](https://addons.mozilla.org/en-US/firefox/addon/search_result_previews/) by some browser extensions, that lets you see a preview image of all the websites that are found my the engine.

![Screenshot_20231014_172842](https://github.com/Ahwxorg/LibreY/assets/6344099/05f3bdde-9b87-4448-90d6-60c8d71e676a)

The extension that is doing that, is sadly non-free. 

Can we do this open source, and for this engine specifically? 😃

**Comment by codedipper** [comment]
Hello! I do not feel comfortable touching the **absolutely proprietary** extension. If you can, right click on the image, and click "Copy Image Link" and send it here, because it might be able to give us a little bit of insight into how this works.

![Screenshot_2023-10-14_13-04-21](https://github.com/Ahwxorg/LibreY/assets/59625582/67365af9-2829-4ee1-b727-b967e0be8099)

**Comment by ShalokShalom** [comment]
blob:https://www.google.com/cda0fb36-bd0c-4a55-b47d-ddfc2536c73a
blob:https://duckduckgo.com/76e58e43-35b0-4294-b959-dc4ea16b2432

**Comment by codedipper** [comment]
These look like a randomly generated URL, and there is no API for search result previews. If we did implement this ourselves, it would require a significant amount of resources for the servers hosting the instances.

**Comment by ShalokShalom** [comment]
This may go a bit overboard, but I have an idea. 

First, I think I have a solution to that: Peer to Peer. 
We could host these images with a service like IPFS. 

Secondly, there is a separate search engine, that fully build on this concept: 
![peekier-searches-peekier](https://github.com/Ahwxorg/LibreY/assets/6344099/14b102b3-7781-4ccb-a2cc-4e547c5d2dcb)

This uses all the screen estate, another problem that I really dislike about other engines. 
[Peekier got deprecated and redirects now to another engine. ](https://thenewleafjournal.com/peekier-search-engine-review/)

I understand if this is out of the scope of this project, and still, this could be the FOSS way of providing such a search experience. 

I know that they did this by tiny PNG files, and the render times were really not as bad, as someone would assume they are. 

I don't know if they used [that](https://tinypng.com/), but there are projects who allow rendering those previews in the browser. 

What do you think of that?

**Comment by davidovski** [comment]
I think this might be out of the scope of LibreX, adding something like this to LibreY by default might introduce an extra level of unneeded complexity. 
Though it might be worth considering working on a free and open source extension that provides this functionality for LibreX/Y, and even other engines. (Maybe even a self-hostable service to proxy connections to external sites with an API?)

**Comment by ShalokShalom** [comment]
Sounds nice. What could this API look like? Is there something established?
