### ISSUE TITLE
Localisation for User Interface text

### ISSUE THREAD

**Issue by davidovski** [Ahwxorg/LibreY#70]
LibreY supports fetching different language's results via the `language` option, however this does not affect elements on the LibreY page itself (ie search buttons etc)

It might be worth considering implementing some form of localisation to the project to allow more people globally to access the project. 

What comes to mind when I think localisation is to use something like gettext to allow for localized strings. However it might be worth implementing a more minimal solution within our codebase itself, for example simply defining strings as an array with different languages as keys.

**Comment by Ahwxorg** [comment]
Could be cool. Do you mean basically making every text element a variable and relying on the community to translate it?

**Comment by davidovski** [comment]
I think that is the best way of doing it, and allowing instance hosts to set a default language that is user-configurable. Obviously IP-geolocation-based is not a good idea, especially with how innaccurate this data can be. 

There are headers within http that most browsers send that request the language of the webpage: `Accept-Language`, however these could be innacurate/missing also as well as being a privacy concern for users of an instance (though these are sent anyway and aren't too different from just having a cookie that relays the same information.) 

It might be worth incorporating a mixture of cookies and this header, that way it is still user-configurable to some extent.
