### ISSUE TITLE
Add more tabs

### ISSUE THREAD

**Issue by tamimology** [Ahwxorg/LibreY#72]
It would be just convenient if the search results tabs match with the ones in Google, i.e. Maps (could be OpenStreetMaps for privacy), , Shopping..etc

This is when searching for any keyword in Google, that could have a shopping option as well
![image](https://github.com/Ahwxorg/LibreY/assets/90429593/8994dc47-99b6-405c-a586-b0570079aef3)

this is when searching for an address in Google
![image](https://github.com/Ahwxorg/LibreY/assets/90429593/f76784e4-2086-470f-a911-aad85a563094)

I searched for the same address above, and no Maps option :(
![image](https://github.com/Ahwxorg/LibreY/assets/90429593/f9e35386-32f6-476d-be4f-cfb4236c2f9b)

**Comment by Ahwxorg** [comment]
I was just yesterday talking about adding Pinterest-frontend Binternet as a tab. Maps could be useful indeed, but a little hard to add, address detection seems a little hard and honestly out of the scope of LibreY. However, if there's a good PR, - that keeps privacy in mind - I will probably merge it.

**Comment by davidovski** [comment]
It might be possible to add maps via OSM, even if it is just a redirect to OSM's search results for that page. I'm not sure if there is any reasonable way to proxy OSM requests via libreY without using javascript to display a map. However, it might be possible to just use their API to get search results for the entered address, which link to the corresponding OSM page for that location. 

As for shopping and news, I'm not sure how useful these actually are to implement: one can easily get news results by searching general so it might not be necessary to implement this.

**Comment by Ahwxorg** [comment]
I checked it, seems possible indeed, but maybe a little clumsy to add a maps button for "wood plank" if someone searches for that? I'm not going to regex a bunch of cities...

**Comment by davidovski** [comment]
Maybe we can offload that sort of work elsewhere: for example we could do a preliminary search on OSM, and if it yeilds no street names / corresponding addresses, then we can omit this from the tabs list. However this could be an extra request that would slow down the load time to the page, and potentially lead to further ratelimits elsewhere, so might not be such a good idea.
 I think adding it to the end of the list wouldnt be too distracting, as if someone did search "wood plank" they probably wouldnt think to search on maps anyway, unless it was indeed something they wanted a location for (?).

**Comment by Ahwxorg** [comment]
Hmm, might be nice to implement then, shouldn't be too hard... I'll look at it!

**Comment by Ahwxorg** [comment]
Closing as `Maps` has been added.

**Comment by tamimology** [comment]
Reopening as the results do not match the search criteria

When I click the first result (which is the one I am after), 

![image](https://github.com/Ahwxorg/LibreY/assets/90429593/9de3dfe5-1f1a-4538-a4ae-2edaff258f25)

it redirects me to the following link
`https://www.openstreetmap.org/node/185058198`

Opening this page, zooming out a bit to check where is it, it turns out to be somewhere else, in this case, somewhere in Canada instead of Melbourne/Australia

![image](https://github.com/Ahwxorg/LibreY/assets/90429593/c0c960be-37ee-4ab2-af5e-9aee06b9a27e)

Even the street name shown is not related to Major Road

![image](https://github.com/Ahwxorg/LibreY/assets/90429593/b662632f-eefd-43dd-9e44-7619f27c85bf)

It is not only with this address, it is for all, and I have checked with a friend of mine on his locally hosted version. Same thing

**Comment by codedipper** [comment]
> It is not only with this address, it is for all, and I have checked with a friend of mine on his locally hosted version.

This is because for street names in particular, OpenStreetMap uses `/way/` to prefix their URLs, than the regular `/node/`. This is why it gives you a different place. Including for cities, which use `/relation/` and also partially mess up the search.

The fix for this would be to use `osm_type` for the URL path. I'm willing to implement this.
