### ISSUE TITLE
[Enhancement]: Add option to filter out results by date

### ISSUE THREAD

**Issue by ahmadyusuf** [Ahwxorg/LibreY#88]
Thanks for your effort, I am using LibreY now as my main search engine.

In many cases, users want to search a keyword and show only results in the last week or days, it is an option in Google search under "Tools" to show results in past hour / week  . . . etc 
Would be great if you support this in LibreY as well

**Comment by Ahwxorg** [comment]
> The before: & after: commands return documents before & after a date. You must provide year-month-day dates or only a year. You can combine both. For example:

> [avengers endgame before:2019]
> [avengers endgame after:2019-04-01]
> [avengers endgame after:2019-03-01 before:2019-03-05 [pic.twitter.com/bo1rSeulbH](https://t.co/bo1rSeulbH)

> — Google SearchLiaison (@searchliaison) [April 9, 2019](https://twitter.com/searchliaison/status/1115707059998052354?ref_src=twsrc%5Etfw)

Does this work?

**Comment by ahmadyusuf** [comment]
Works perfectly, thank you very much

**Comment by Ahwxorg** [comment]
Alright! No problem, closing this issue then.
