### ISSUE TITLE
Deprecated: Creation of dynamic property

### ISSUE THREAD

**Issue by NF075** [Ahwxorg/LibreY#91]
Hi
I follow procedure for host my own instance
Everything working
Except for every search i do i have this on search result page :

Deprecated: Creation of dynamic property TextSearch::$query is deprecated in /home/runner/LibreY/engines/text/text.php on line 4

Deprecated: Creation of dynamic property TextSearch::$page is deprecated in /home/runner/LibreY/engines/text/text.php on line 5

Deprecated: Creation of dynamic property TextSearch::$opts is deprecated in /home/runner/LibreY/engines/text/text.php on line 6

Deprecated: Creation of dynamic property TextSearch::$engine is deprecated in /home/runner/LibreY/engines/text/text.php on line 8

Deprecated: Creation of dynamic property GoogleRequest::$query is deprecated in /home/runner/LibreY/misc/search_engine.php on line 6

Deprecated: Creation of dynamic property GoogleRequest::$page is deprecated in /home/runner/LibreY/misc/search_engine.php on line 7

Deprecated: Creation of dynamic property GoogleRequest::$mh is deprecated in /home/runner/LibreY/misc/search_engine.php on line 8

Deprecated: Creation of dynamic property GoogleRequest::$opts is deprecated in /home/runner/LibreY/misc/search_engine.php on line 9

Deprecated: Creation of dynamic property GoogleRequest::$url is deprecated in /home/runner/LibreY/misc/search_engine.php on line 11

Deprecated: Creation of dynamic property GoogleRequest::$ch is deprecated in /home/runner/LibreY/misc/search_engine.php on line 18

Deprecated: Creation of dynamic property TextSearch::$engine_request is deprecated in /home/runner/LibreY/engines/text/text.php on line 18

Deprecated: Creation of dynamic property WikipediaRequest::$query is deprecated in /home/runner/LibreY/misc/search_engine.php on line 6

Deprecated: Creation of dynamic property WikipediaRequest::$page is deprecated in /home/runner/LibreY/misc/search_engine.php on line 7

Deprecated: Creation of dynamic property WikipediaRequest::$mh is deprecated in /home/runner/LibreY/misc/search_engine.php on line 8

Deprecated: Creation of dynamic property WikipediaRequest::$opts is deprecated in /home/runner/LibreY/misc/search_engine.php on line 9

Deprecated: Creation of dynamic property WikipediaRequest::$wikipedia_domain is deprecated in /home/runner/LibreY/engines/special/wikipedia.php on line 4

Deprecated: Creation of dynamic property WikipediaRequest::$url is deprecated in /home/runner/LibreY/misc/search_engine.php on line 11

Deprecated: Creation of dynamic property WikipediaRequest::$ch is deprecated in /home/runner/LibreY/misc/search_engine.php on line 18

Deprecated: Creation of dynamic property TextSearch::$special_request is deprecated in /home/runner/LibreY/engines/text/text.php on line 35

What is i do wrong ?
Thank you .
( With latest Libre X commit i don't have this.
I merge to Libre Y and this errors appairing )

**Comment by alithechemist** [comment]
I think you just have a too new php version, where some methods are working but throwing a deprecation notice.
You can:
 - Downgrade php
 - Rewrite the code so it runs without notices
 - Keep it as it is but suppress the notices by changing  php.ini 
 
Just out of curiosity what version of php are you using? here https://php.watch/versions/8.2/dynamic-properties-deprecated looks like it affects php 8.2+

**Comment by NF075** [comment]
Yes exactly php 8.2+

alithechemist thank you very much for your attempt to help

It seem Libre X is dead
The best project ; too bad
Libre Y is too complicated

I'm going back to Whoogle Search and searx

**Comment by davidovski** [comment]
Do these deprecated warnings affect the way that the site works? It might be worth keeping this issue open since its probably worth removing these deprecated features from the code to ensure that it will remain functioning in future updates of php.

Which exact version of php are you using? Might help when trying to solve this issue

**Comment by NF075** [comment]
As you want...

No, the site works perfectly
Except half of the results page with these warnings
For continuous use, it is very uncomfortable
In the end it's too annoying

php 8.2.6

**Comment by alithechemist** [comment]
@NF075  you can also change the logging in php.ini. 
Normally in production machines those logs should not be visible at all. you should shaveee in your php.ini (the fpm i guess), something like 
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
From what you wrote i wildly guess that you have 
error_reporting = E_ALL 

Maybe this can swipe the problem under the carpet for now but not for long.

**Comment by Ahwxorg** [comment]
I will look into this somewhere tomorrow.

Does Debian 10 stable ship with PHP-8.2 or higher? That's usually the go-to for me and a lot of other hosting providers.

**Comment by davidovski** [comment]
Checked with php8.2 and php8.3, #92 fixes all deprication warnings that I am able to spot. Please try it and let me know if there are any that i missed

**Comment by NF075** [comment]
No, not the stable version. 8.2.6. It must be installed manually.
Thanks. ...

**Comment by Ahwxorg** [comment]
@NF075 are you using a shared PHP host? If not, why is your config not default? You should not get error messages on the page itself with the default configuration...

**Comment by davidovski** [comment]
Tested #92 on php 8.2.6, no deprecation warnings visible. Just need to wait for that PR to be accepted and you should be good to go 
![image](https://github.com/Ahwxorg/LibreY/assets/16747851/3b6d9c19-aaf4-41af-9241-95f3ca70aeb2)

**Comment by Ahwxorg** [comment]
Accepting the PR now.

**Comment by Ahwxorg** [comment]
What? WSL??? Are you hosting PHP on Windows 11???

**Comment by davidovski** [comment]
This issue can be closed now since the deprication warnings have been fixed. 

> No. Debian embedded in winwdows 11.
I'd recomend running LibreY on a linux VPS or a server running linux; do you have windows 11 running on your server or if you are just trying to test it locally?

The debian version of on WSL if i remember correctly has some slight modifications so this might be the reason why these settings are non-default. (unless you have changed them without realising). 

Other than that I see no reason why LibreY shouldn't be able to run perfectly fine on WSL2, though it is a questionable choice for hosting.

**Comment by NF075** [comment]
Excuse me. English is not my first language
You’re right, that’s what I meant.
WSL.
Edit:
With whoogel , searx , librex.
 It works.
Thanks
Best regards.

**Comment by NF075** [comment]
Thank you very much gentlemen with the changes made. Now everything works perfectly.  
Commit cace169....

Best regards. And again thanks....

**Comment by NF075** [comment]
Not on my server. But as you say locally for testing. For the moment.
I think your right, I have changed settings without realising. In my config
.
But now with latest commit, everything work very well. It's great. Thank
you very much. Regards. ...
