### ISSUE TITLE
PHP 8.3 Release

### ISSUE THREAD

**Issue by codedipper** [Ahwxorg/LibreY#93]
See:
https://www.php.net/releases/8.3/en.php

This shouldn't affect any of our code right now, nor the documentation, right?
I can test in a Debian virtual machine, it's packaged in experimental:
https://packages.debian.org/experimental/php8.3

**Comment by codedipper** [comment]
We will have to update things for Docker, see Alpine Linux edge packages:
https://pkgs.alpinelinux.org/packages?name=php83*&branch=edge&repo=&arch=&maintainer=

Please note that php-apcu is not packaged in neither Debian nor Alpine.

**Comment by Ahwxorg** [comment]
> This shouldn't affect any of our code right now, nor the documentation, right?

I will do some testing soon, unless you do. I don't think it will but I might be wrong. @davidovski seems to know the codebase in it's current form best.

> Please note that php-apcu is not packaged in neither Debian nor Alpine.

Tagging @davidovski here

**Comment by davidovski** [comment]
I think until pecl-apcu is provided with 8.3 in alpine, we should hold off updating the docker image to this version. If the code works with 8.3 other than that, I dont see any reason not to support it. I will do a bit more testing with it to see if there are any edge cases that might be missed, but I have been using 8.3 release candidates for development recently and havent noticed any major problems.

**Comment by davidovski** [comment]
Scratch that, php83-pecl-apcu is on the edge branch of alpine: its what I have been using for development this whole time! Currently the docker image only uses alpine 3.18, which does not have php83 yet, however I believe that the next release of alpine will contain these packages. We could switch the alpine image to edge to allow us to use php8.3 but I dont see any immediate reason to do so.

**Comment by codedipper** [comment]
> Unrelated; @codedipper when will your Matrix be back up?

Short answer: When I feel like it and have time.

Long answer: A really long time. I still don't have an email server (`dig -t MX +short revvy.de`) and I still haven't setup nginx (using OpenHTTPd), both of which I need to have before I start restoring any of my services. Even some of my fully static domains I still don't have up (`f.revvy.de`, `rc.revvy.de`) yet. School and other responsibilities don't help either. After living on Tails and later on an external HDD, I have my new PC (`curl https://revvy.de/fetch`) and am starting to set it up.
