### ISSUE TITLE
image search doesn't works anymore

### ISSUE THREAD

**Issue by jkumeboshi** [Ahwxorg/LibreY#98]
Looks like that Qwant image search has dropped support for the "lite" url or something similar, since image search as stopped working in any LibreY instance.

**Comment by ahmadyusuf** [comment]
My image search works on my self hosted instance but it is very slow to an extent that makes it unusable

**Comment by Ahwxorg** [comment]
I had the same issue. I will be looking into it.

**Comment by Ahwxorg** [comment]
Would a solution be to use Pinterest for images?

**Comment by michelematteini** [comment]
I fixed it here https://github.com/michelematteini/librex/commit/7743b87081a60eff9cff5fd42d2e46f1f15a046a
but i can't make a pull request since I forked LibreX

**Comment by michelematteini** [comment]
Created from a separate branch

**Comment by Ahwxorg** [comment]
Should work on the newest commit!
